AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFront > S3 for Angular web app
  Naming convention, [stage]--[repo]--[branch]--[eyecatcher]--r
  Redirect to SSL, custom DomainName, Edge Gzip, Angular redirects 

Parameters:

  AcmCertificateArn:
    Description: The ARN of a certificate from AWS Certificate Manager (ACM)
    Default: arn:aws:acm:us-east-1:111:certificate/222
    Type: String

  CloudFrontCname:
    Description: Custom domain name to use (www.yourdomain.com).  Will prefix this with stageName--
    Type: String
    Default: www.yourdomain.com
    AllowedPattern : (([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.){2,}([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]){2,}
    ConstraintDescription : Must be a valid FQDN   

Conditions: 
  CreateStagingResources: !Equals [ !Select [ "0", !Split [ '--', !Ref 'AWS::StackName' ] ], prod ]

Mappings: 
  NestedStacks: 
    infrastructure: 
      "angularCustomDomain": "cloudfront/angular-custom-domain.yaml?versionid=YourS3VersionId"    
                  
Resources:    
#### DNS, Cloudfront, S3 bucket for hosing Angular app
  CloudFront:  
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 
        - https://s3.${AWS::Region}.amazonaws.com/${NestedStacksS3Bucket}/nested-stacks/${url}
        - { url: !FindInMap [NestedStacks, infrastructure, angularCustomDomain] }

      Parameters:
        Stage: !Select [ "0", !Split [ '--', !Ref 'AWS::StackName' ] ]
        Branch: !Select [ "2", !Split [ '--', !Ref 'AWS::StackName' ] ]
        AcmCertificateArn: !Ref AcmCertificateArn
        Route53HostedZoneId: Z2FDTNDATAQYW2
        CloudFrontCname: !Ref CloudFrontCname

  CloudFrontStaging:  
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateStagingResources
    Properties:
      TemplateURL: !Sub 
        - https://s3.${AWS::Region}.amazonaws.com/${NestedStacksS3Bucket}/nested-stacks/${url}
        - { url: !FindInMap [NestedStacks, infrastructure, angularCustomDomain] }

      Parameters:
        Stage: staging
        Branch: !Select [ "2", !Split [ '--', !Ref 'AWS::StackName' ] ]
        AcmCertificateArn: !Ref AcmCertificateArn
        Route53HostedZoneId: Z2FDTNDATAQYW2
        CloudFrontCname: !Ref CloudFrontCname   
####END Cloudfront and DNS stuff  

Outputs:
  Version:
    Description: Angular web app template version
    Value: 1.0.0

  CloudFront:
    Description: CloudFront ID
    Value: !GetAtt CloudFront.Outputs.CloudFront
  CNAME:
    Description: Custom domain for Cloudfront
    Value: !GetAtt CloudFront.Outputs.CNAME
  URL:
    Description: App URL
    Value: !GetAtt CloudFront.Outputs.AppURL

  #staging output
  CloudFrontStaging:
    Description: Staging CloudFront ID
    Value: !If [CreateStagingResources, !GetAtt CloudFrontStaging.Outputs.CloudFront, NA]
  CNAMEStaging:
    Description: Staging Custom domain for Cloudfront
    Value: !If [CreateStagingResources, !GetAtt CloudFrontStaging.Outputs.CNAME, NA] 
  URLStaging:
    Description: Staging App URL
    Value: !If [CreateStagingResources, !GetAtt CloudFront.Outputs.AppURL, NA]
  #end staging output         
